# Miniconda stuff shamelessly copied from
# https://gist.github.com/dan-blanchard/7045057
# and
# https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: c

matrix:
  include:
    # do one build run with our minimum dependencies
    # (or, well, at least the lowest version number that is available through
    #  anaconda..)
    - os: linux
      env: PYTHON_VERSION=3.7

    - os: osx
      env: PYTHON_VERSION=3.7

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS="MacOSX";
    else
      export OS="Linux";
    fi
  # Python and related stuff
  - if [[ "${PYTHON_VERSION:0:1}" == '2' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-${OS}-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-${OS}-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels conda-forge
  - conda config --add channels conda-forge
  - conda update -q --yes conda
  # Installs required packages
  - conda install --yes -q pip python=$PYTHON_VERSION msnoise obspy bottleneck

install:
  - python setup.py install
  - cd

script:
  - mkdir MSNoiseSARATest
  - cd MSNoiseSARATest
  - msnoise db init --tech 1
  - msnoise config set plugins=msnoise_sara
  - msnoise p sara install
  - msnoise p sara
